services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: spring_batch
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
